// This file has been automatically generated. Don't edit it.

package goobs

import (
	config "github.com/andreykaipov/goobs/api/requests/config"
	filters "github.com/andreykaipov/goobs/api/requests/filters"
	general "github.com/andreykaipov/goobs/api/requests/general"
	inputs "github.com/andreykaipov/goobs/api/requests/inputs"
	mediainputs "github.com/andreykaipov/goobs/api/requests/media_inputs"
	outputs "github.com/andreykaipov/goobs/api/requests/outputs"
	rconfig "github.com/andreykaipov/goobs/api/requests/rconfig"
	record "github.com/andreykaipov/goobs/api/requests/record"
	sceneitems "github.com/andreykaipov/goobs/api/requests/scene_items"
	scenes "github.com/andreykaipov/goobs/api/requests/scenes"
	sources "github.com/andreykaipov/goobs/api/requests/sources"
	stream "github.com/andreykaipov/goobs/api/requests/stream"
	transitions "github.com/andreykaipov/goobs/api/requests/transitions"
	ui "github.com/andreykaipov/goobs/api/requests/ui"
)

func GetRequestResponseForType(name string) interface{} {
	switch name {
	case "GetPersistentData":
		return &config.GetPersistentDataResponse{}
	case "SetPersistentData":
		return &config.SetPersistentDataResponse{}
	case "GetSceneCollectionList":
		return &config.GetSceneCollectionListResponse{}
	case "SetCurrentSceneCollection":
		return &config.SetCurrentSceneCollectionResponse{}
	case "CreateSceneCollection":
		return &config.CreateSceneCollectionResponse{}
	case "GetProfileList":
		return &config.GetProfileListResponse{}
	case "SetCurrentProfile":
		return &config.SetCurrentProfileResponse{}
	case "CreateProfile":
		return &config.CreateProfileResponse{}
	case "RemoveProfile":
		return &config.RemoveProfileResponse{}
	case "GetProfileParameter":
		return &config.GetProfileParameterResponse{}
	case "SetProfileParameter":
		return &config.SetProfileParameterResponse{}
	case "GetVideoSettings":
		return &config.GetVideoSettingsResponse{}
	case "SetVideoSettings":
		return &config.SetVideoSettingsResponse{}
	case "GetStreamServiceSettings":
		return &config.GetStreamServiceSettingsResponse{}
	case "SetStreamServiceSettings":
		return &config.SetStreamServiceSettingsResponse{}
	case "GetSourceFilterList":
		return &filters.GetSourceFilterListResponse{}
	case "GetSourceFilterDefaultSettings":
		return &filters.GetSourceFilterDefaultSettingsResponse{}
	case "CreateSourceFilter":
		return &filters.CreateSourceFilterResponse{}
	case "RemoveSourceFilter":
		return &filters.RemoveSourceFilterResponse{}
	case "SetSourceFilterName":
		return &filters.SetSourceFilterNameResponse{}
	case "GetSourceFilter":
		return &filters.GetSourceFilterResponse{}
	case "SetSourceFilterIndex":
		return &filters.SetSourceFilterIndexResponse{}
	case "SetSourceFilterSettings":
		return &filters.SetSourceFilterSettingsResponse{}
	case "SetSourceFilterEnabled":
		return &filters.SetSourceFilterEnabledResponse{}
	case "GetVersion":
		return &general.GetVersionResponse{}
	case "GetStats":
		return &general.GetStatsResponse{}
	case "BroadcastCustomEvent":
		return &general.BroadcastCustomEventResponse{}
	case "CallVendorRequest":
		return &general.CallVendorRequestResponse{}
	case "GetHotkeyList":
		return &general.GetHotkeyListResponse{}
	case "TriggerHotkeyByName":
		return &general.TriggerHotkeyByNameResponse{}
	case "TriggerHotkeyByKeySequence":
		return &general.TriggerHotkeyByKeySequenceResponse{}
	case "Sleep":
		return &general.SleepResponse{}
	case "GetInputList":
		return &inputs.GetInputListResponse{}
	case "GetInputKindList":
		return &inputs.GetInputKindListResponse{}
	case "GetSpecialInputs":
		return &inputs.GetSpecialInputsResponse{}
	case "CreateInput":
		return &inputs.CreateInputResponse{}
	case "RemoveInput":
		return &inputs.RemoveInputResponse{}
	case "SetInputName":
		return &inputs.SetInputNameResponse{}
	case "GetInputDefaultSettings":
		return &inputs.GetInputDefaultSettingsResponse{}
	case "GetInputSettings":
		return &inputs.GetInputSettingsResponse{}
	case "SetInputSettings":
		return &inputs.SetInputSettingsResponse{}
	case "GetInputMute":
		return &inputs.GetInputMuteResponse{}
	case "SetInputMute":
		return &inputs.SetInputMuteResponse{}
	case "ToggleInputMute":
		return &inputs.ToggleInputMuteResponse{}
	case "GetInputVolume":
		return &inputs.GetInputVolumeResponse{}
	case "SetInputVolume":
		return &inputs.SetInputVolumeResponse{}
	case "GetInputAudioBalance":
		return &inputs.GetInputAudioBalanceResponse{}
	case "SetInputAudioBalance":
		return &inputs.SetInputAudioBalanceResponse{}
	case "GetInputAudioSyncOffset":
		return &inputs.GetInputAudioSyncOffsetResponse{}
	case "SetInputAudioSyncOffset":
		return &inputs.SetInputAudioSyncOffsetResponse{}
	case "GetInputAudioMonitorType":
		return &inputs.GetInputAudioMonitorTypeResponse{}
	case "SetInputAudioMonitorType":
		return &inputs.SetInputAudioMonitorTypeResponse{}
	case "GetInputAudioTracks":
		return &inputs.GetInputAudioTracksResponse{}
	case "SetInputAudioTracks":
		return &inputs.SetInputAudioTracksResponse{}
	case "GetInputPropertiesListPropertyItems":
		return &inputs.GetInputPropertiesListPropertyItemsResponse{}
	case "PressInputPropertiesButton":
		return &inputs.PressInputPropertiesButtonResponse{}
	case "GetMediaInputStatus":
		return &mediainputs.GetMediaInputStatusResponse{}
	case "SetMediaInputCursor":
		return &mediainputs.SetMediaInputCursorResponse{}
	case "OffsetMediaInputCursor":
		return &mediainputs.OffsetMediaInputCursorResponse{}
	case "TriggerMediaInputAction":
		return &mediainputs.TriggerMediaInputActionResponse{}
	case "GetVirtualCamStatus":
		return &outputs.GetVirtualCamStatusResponse{}
	case "ToggleVirtualCam":
		return &outputs.ToggleVirtualCamResponse{}
	case "StartVirtualCam":
		return &outputs.StartVirtualCamResponse{}
	case "StopVirtualCam":
		return &outputs.StopVirtualCamResponse{}
	case "GetReplayBufferStatus":
		return &outputs.GetReplayBufferStatusResponse{}
	case "ToggleReplayBuffer":
		return &outputs.ToggleReplayBufferResponse{}
	case "StartReplayBuffer":
		return &outputs.StartReplayBufferResponse{}
	case "StopReplayBuffer":
		return &outputs.StopReplayBufferResponse{}
	case "SaveReplayBuffer":
		return &outputs.SaveReplayBufferResponse{}
	case "GetLastReplayBufferReplay":
		return &outputs.GetLastReplayBufferReplayResponse{}
	case "GetRecordDirectory":
		return &rconfig.GetRecordDirectoryResponse{}
	case "GetRecordStatus":
		return &record.GetRecordStatusResponse{}
	case "ToggleRecord":
		return &record.ToggleRecordResponse{}
	case "StartRecord":
		return &record.StartRecordResponse{}
	case "StopRecord":
		return &record.StopRecordResponse{}
	case "ToggleRecordPause":
		return &record.ToggleRecordPauseResponse{}
	case "PauseRecord":
		return &record.PauseRecordResponse{}
	case "ResumeRecord":
		return &record.ResumeRecordResponse{}
	case "GetSceneItemList":
		return &sceneitems.GetSceneItemListResponse{}
	case "GetGroupItemList":
		return &sceneitems.GetGroupItemListResponse{}
	case "GetSceneItemId":
		return &sceneitems.GetSceneItemIdResponse{}
	case "CreateSceneItem":
		return &sceneitems.CreateSceneItemResponse{}
	case "RemoveSceneItem":
		return &sceneitems.RemoveSceneItemResponse{}
	case "DuplicateSceneItem":
		return &sceneitems.DuplicateSceneItemResponse{}
	case "GetSceneItemTransform":
		return &sceneitems.GetSceneItemTransformResponse{}
	case "SetSceneItemTransform":
		return &sceneitems.SetSceneItemTransformResponse{}
	case "GetSceneItemEnabled":
		return &sceneitems.GetSceneItemEnabledResponse{}
	case "SetSceneItemEnabled":
		return &sceneitems.SetSceneItemEnabledResponse{}
	case "GetSceneItemLocked":
		return &sceneitems.GetSceneItemLockedResponse{}
	case "SetSceneItemLocked":
		return &sceneitems.SetSceneItemLockedResponse{}
	case "GetSceneItemIndex":
		return &sceneitems.GetSceneItemIndexResponse{}
	case "SetSceneItemIndex":
		return &sceneitems.SetSceneItemIndexResponse{}
	case "GetSceneItemBlendMode":
		return &sceneitems.GetSceneItemBlendModeResponse{}
	case "SetSceneItemBlendMode":
		return &sceneitems.SetSceneItemBlendModeResponse{}
	case "GetSceneList":
		return &scenes.GetSceneListResponse{}
	case "GetGroupList":
		return &scenes.GetGroupListResponse{}
	case "GetCurrentProgramScene":
		return &scenes.GetCurrentProgramSceneResponse{}
	case "SetCurrentProgramScene":
		return &scenes.SetCurrentProgramSceneResponse{}
	case "GetCurrentPreviewScene":
		return &scenes.GetCurrentPreviewSceneResponse{}
	case "SetCurrentPreviewScene":
		return &scenes.SetCurrentPreviewSceneResponse{}
	case "CreateScene":
		return &scenes.CreateSceneResponse{}
	case "RemoveScene":
		return &scenes.RemoveSceneResponse{}
	case "SetSceneName":
		return &scenes.SetSceneNameResponse{}
	case "GetSceneSceneTransitionOverride":
		return &scenes.GetSceneSceneTransitionOverrideResponse{}
	case "SetSceneSceneTransitionOverride":
		return &scenes.SetSceneSceneTransitionOverrideResponse{}
	case "GetSourceActive":
		return &sources.GetSourceActiveResponse{}
	case "GetSourceScreenshot":
		return &sources.GetSourceScreenshotResponse{}
	case "SaveSourceScreenshot":
		return &sources.SaveSourceScreenshotResponse{}
	case "GetStreamStatus":
		return &stream.GetStreamStatusResponse{}
	case "ToggleStream":
		return &stream.ToggleStreamResponse{}
	case "StartStream":
		return &stream.StartStreamResponse{}
	case "StopStream":
		return &stream.StopStreamResponse{}
	case "SendStreamCaption":
		return &stream.SendStreamCaptionResponse{}
	case "GetTransitionKindList":
		return &transitions.GetTransitionKindListResponse{}
	case "GetSceneTransitionList":
		return &transitions.GetSceneTransitionListResponse{}
	case "GetCurrentSceneTransition":
		return &transitions.GetCurrentSceneTransitionResponse{}
	case "SetCurrentSceneTransition":
		return &transitions.SetCurrentSceneTransitionResponse{}
	case "SetCurrentSceneTransitionDuration":
		return &transitions.SetCurrentSceneTransitionDurationResponse{}
	case "SetCurrentSceneTransitionSettings":
		return &transitions.SetCurrentSceneTransitionSettingsResponse{}
	case "GetCurrentSceneTransitionCursor":
		return &transitions.GetCurrentSceneTransitionCursorResponse{}
	case "TriggerStudioModeTransition":
		return &transitions.TriggerStudioModeTransitionResponse{}
	case "SetTBarPosition":
		return &transitions.SetTBarPositionResponse{}
	case "GetStudioModeEnabled":
		return &ui.GetStudioModeEnabledResponse{}
	case "SetStudioModeEnabled":
		return &ui.SetStudioModeEnabledResponse{}
	case "OpenInputPropertiesDialog":
		return &ui.OpenInputPropertiesDialogResponse{}
	case "OpenInputFiltersDialog":
		return &ui.OpenInputFiltersDialogResponse{}
	case "OpenInputInteractDialog":
		return &ui.OpenInputInteractDialogResponse{}
	case "GetMonitorList":
		return &ui.GetMonitorListResponse{}
	default:
		return nil
	}
}
