// This file has been automatically generated. Don't edit it.

package events

func GetType(name string) interface{} {
	switch name {
	case "CurrentSceneCollectionChanging":
		return &CurrentSceneCollectionChanging{}
	case "CurrentSceneCollectionChanged":
		return &CurrentSceneCollectionChanged{}
	case "SceneCollectionListChanged":
		return &SceneCollectionListChanged{}
	case "CurrentProfileChanging":
		return &CurrentProfileChanging{}
	case "CurrentProfileChanged":
		return &CurrentProfileChanged{}
	case "ProfileListChanged":
		return &ProfileListChanged{}
	case "SourceFilterListReindexed":
		return &SourceFilterListReindexed{}
	case "SourceFilterCreated":
		return &SourceFilterCreated{}
	case "SourceFilterRemoved":
		return &SourceFilterRemoved{}
	case "SourceFilterNameChanged":
		return &SourceFilterNameChanged{}
	case "SourceFilterEnableStateChanged":
		return &SourceFilterEnableStateChanged{}
	case "ExitStarted":
		return &ExitStarted{}
	case "InputCreated":
		return &InputCreated{}
	case "InputRemoved":
		return &InputRemoved{}
	case "InputNameChanged":
		return &InputNameChanged{}
	case "InputActiveStateChanged":
		return &InputActiveStateChanged{}
	case "InputShowStateChanged":
		return &InputShowStateChanged{}
	case "InputMuteStateChanged":
		return &InputMuteStateChanged{}
	case "InputVolumeChanged":
		return &InputVolumeChanged{}
	case "InputAudioBalanceChanged":
		return &InputAudioBalanceChanged{}
	case "InputAudioSyncOffsetChanged":
		return &InputAudioSyncOffsetChanged{}
	case "InputAudioTracksChanged":
		return &InputAudioTracksChanged{}
	case "InputAudioMonitorTypeChanged":
		return &InputAudioMonitorTypeChanged{}
	case "InputVolumeMeters":
		return &InputVolumeMeters{}
	case "MediaInputPlaybackStarted":
		return &MediaInputPlaybackStarted{}
	case "MediaInputPlaybackEnded":
		return &MediaInputPlaybackEnded{}
	case "MediaInputActionTriggered":
		return &MediaInputActionTriggered{}
	case "StreamStateChanged":
		return &StreamStateChanged{}
	case "RecordStateChanged":
		return &RecordStateChanged{}
	case "ReplayBufferStateChanged":
		return &ReplayBufferStateChanged{}
	case "VirtualcamStateChanged":
		return &VirtualcamStateChanged{}
	case "ReplayBufferSaved":
		return &ReplayBufferSaved{}
	case "SceneItemCreated":
		return &SceneItemCreated{}
	case "SceneItemRemoved":
		return &SceneItemRemoved{}
	case "SceneItemListReindexed":
		return &SceneItemListReindexed{}
	case "SceneItemEnableStateChanged":
		return &SceneItemEnableStateChanged{}
	case "SceneItemLockStateChanged":
		return &SceneItemLockStateChanged{}
	case "SceneItemSelected":
		return &SceneItemSelected{}
	case "SceneItemTransformChanged":
		return &SceneItemTransformChanged{}
	case "SceneCreated":
		return &SceneCreated{}
	case "SceneRemoved":
		return &SceneRemoved{}
	case "SceneNameChanged":
		return &SceneNameChanged{}
	case "CurrentProgramSceneChanged":
		return &CurrentProgramSceneChanged{}
	case "CurrentPreviewSceneChanged":
		return &CurrentPreviewSceneChanged{}
	case "SceneListChanged":
		return &SceneListChanged{}
	case "CurrentSceneTransitionChanged":
		return &CurrentSceneTransitionChanged{}
	case "CurrentSceneTransitionDurationChanged":
		return &CurrentSceneTransitionDurationChanged{}
	case "SceneTransitionStarted":
		return &SceneTransitionStarted{}
	case "SceneTransitionEnded":
		return &SceneTransitionEnded{}
	case "SceneTransitionVideoEnded":
		return &SceneTransitionVideoEnded{}
	case "StudioModeStateChanged":
		return &StudioModeStateChanged{}
	case "ScreenshotSaved":
		return &ScreenshotSaved{}
	case "VendorEvent":
		return &VendorEvent{}
	case "CustomEvent":
		return &CustomEvent{}
	default:
		return nil
	}
}
