name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_run:
    workflows: [image]
    types: [completed]

permissions:
  contents: read
  pull-requests: read

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      go: steps.filter.outputs.go
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          go:
          - '**/*.go'
          - go.mod
          - go.sum

  test:
    needs: check-changes
    if: needs.check-changes.outputs.go == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: magnetikonline/action-golang-cache@v3
      with:
        go-version-file: go.mod
    - run: make test
    - run: go tool cover -func coverall.out

  generate:
    needs: check-changes
    if: needs.check-changes.outputs.go == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: magnetikonline/action-golang-cache@v3
      with:
        go-version-file: go.mod
    - run: make clean && make generate
    - name: Ensure generated code is already checked in
      if: success()
      run: |
        files="$(git diff --name-only)"
        if [ -z "$files" ]; then exit 0; fi
        echo "Files with diffs:"
        echo "$files"
        echo
        echo
        git diff
        exit 1
