name: generate

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  generate:
    strategy:
      matrix:
        go-version: [^1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Go modules
        run: go mod download

      - name: Generate
        run: make generate

      - name: Build
        run: go build -v ./...
